# Generated by Django 4.2.1 on 2023-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federal_entities', '0001_initial'),
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField()),
                ('locality', models.CharField(blank=True, null=True)),
                ('federal_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='federal_entities.federalentitymodel')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='municipalities.municipalitymodel')),
            ],
        ),
    ]
